{% set name = "python-gnupg" %}
{% set version = "0.5.4" %}
{% set sha256 = "f2fdb5fb29615c77c2743e1cb3d9314353a6e87b10c37d238d91ae1c6feae086" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=2.7

  run:
    - python >=2.7

test:
  imports:
    - gnupg

about:
  home: http://pythonhosted.org/python-gnupg
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A wrapper for the Gnu Privacy Guard (GPG or GnuPG)

extra:
  recipe-maintainers:
    - vamega
