{% set name = "python-gnupg" %}
{% set version = "0.5.3" %}
{% set sha256 = "290d8ddb9cd63df96cfe9284b9b265f19fd6e145e5582dc58fd7271f026d0a47" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=2.7

  run:
    - python >=2.7

test:
  imports:
    - gnupg

about:
  home: http://pythonhosted.org/python-gnupg
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A wrapper for the Gnu Privacy Guard (GPG or GnuPG)

extra:
  recipe-maintainers:
    - vamega
